# Use a Python base image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt


# Copy the application files into the container
COPY . .

# Expose the FastAPI port
EXPOSE 8501


# Start the Streamlit application

CMD ["streamlit", "run", "streamlit_app.py", "--server.port", "8501"]
