# Use a Python base image
FROM python:3.12-slim-bullseye


#For TLS
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       gnupg \
       ca-certificates \
       curl \
       netcat \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory in the container
WORKDIR /app



# Copy the requirements file into the container
COPY requirements.txt .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt


# Copy the application files into the container
COPY . .

# Expose the FastAPI port
EXPOSE 8000


# Start the FastAPI application (using uvicorn)

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
