version: "3.9"
services:

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=shopping_app_database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3306:3306"
    volumes:
      - ./resources/db-migrations:/docker-entrypoint-initdb.d/
    command: --default-authentication-plugin=mysql_native_password

  redis:
    container_name: "redis"
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  web:
    image: "chaibukra/ai_shopping_website_with_extra_features_gimini"
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - /.env.docker
    volumes:
      - .:/app
    restart: always

  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    restart: always
    depends_on:
      - web # Ensures FastAPI starts first
    command: sh -c "streamlit run ui/Home.py"
    env_file:
      - /.env.docker
    volumes:
      - .:/app


volumes:
  mysql-data:
